#include <map>

#include <Onyx/Core.h>

#include "charkeys.h"

char ck::all[95] = {
    ' ', '\'', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
    ';', '=', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
    'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '[', '\\',
    ']', '`', '!', '"'
};

std::map<char, Onyx::Key> charToKeyMap = {
    { ' ', Onyx::Key::Space },
    { '\'', Onyx::Key::Apostrophe },
    { ',', Onyx::Key::Comma },
    { '-', Onyx::Key::Minus },
    { '.', Onyx::Key::Period },
    { '/', Onyx::Key::Slash },
    { '0', Onyx::Key::Num0 },
    { '1', Onyx::Key::Num1 },
    { '2', Onyx::Key::Num2 },
    { '3', Onyx::Key::Num3 },
    { '4', Onyx::Key::Num4 },
    { '5', Onyx::Key::Num5 },
    { '6', Onyx::Key::Num6 },
    { '7', Onyx::Key::Num7 },
    { '8', Onyx::Key::Num8 },
    { '9', Onyx::Key::Num9 },
    { ';', Onyx::Key::Semicolon },
    { '=', Onyx::Key::Equal },
    { 'a', Onyx::Key::A },
    { 'b', Onyx::Key::B },
    { 'c', Onyx::Key::C },
    { 'd', Onyx::Key::D },
    { 'e', Onyx::Key::E },
    { 'f', Onyx::Key::F },
    { 'g', Onyx::Key::G },
    { 'h', Onyx::Key::H },
    { 'i', Onyx::Key::I },
    { 'j', Onyx::Key::J },
    { 'k', Onyx::Key::K },
    { 'l', Onyx::Key::L },
    { 'm', Onyx::Key::M },
    { 'n', Onyx::Key::N },
    { 'o', Onyx::Key::O },
    { 'p', Onyx::Key::P },
    { 'q', Onyx::Key::Q },
    { 'r', Onyx::Key::R },
    { 's', Onyx::Key::S },
    { 't', Onyx::Key::T },
    { 'u', Onyx::Key::U },
    { 'v', Onyx::Key::V },
    { 'w', Onyx::Key::W },
    { 'x', Onyx::Key::X },
    { 'y', Onyx::Key::Y },
    { 'z', Onyx::Key::Z },
    { '[', Onyx::Key::LeftBracket },
    { '\\', Onyx::Key::Backslash },
    { ']', Onyx::Key::RightBracket },
    { '`', Onyx::Key::GraveAccent },
    { '!', Onyx::Key::World1 },
    { '"', Onyx::Key::World2 }
};

std::map<Onyx::Key, char> keyToCharMap = {
    { Onyx::Key::Space, ' ' },
    { Onyx::Key::Apostrophe, '\'' },
    { Onyx::Key::Comma, ',' },
    { Onyx::Key::Minus, '-' },
    { Onyx::Key::Period, '.' },
    { Onyx::Key::Slash, '/' },
    { Onyx::Key::Num0, '0' },
    { Onyx::Key::Num1, '1' },
    { Onyx::Key::Num2, '2' },
    { Onyx::Key::Num3, '3' },
    { Onyx::Key::Num4, '4' },
    { Onyx::Key::Num5, '5' },
    { Onyx::Key::Num6, '6' },
    { Onyx::Key::Num7, '7' },
    { Onyx::Key::Num8, '8' },
    { Onyx::Key::Num9, '9' },
    { Onyx::Key::Semicolon, ';' },
    { Onyx::Key::Equal, '=' },
    { Onyx::Key::A, 'a' },
    { Onyx::Key::B, 'b' },
    { Onyx::Key::C, 'c' },
    { Onyx::Key::D, 'd' },
    { Onyx::Key::E, 'e' },
    { Onyx::Key::F, 'f' },
    { Onyx::Key::G, 'g' },
    { Onyx::Key::H, 'h' },
    { Onyx::Key::I, 'i' },
    { Onyx::Key::J, 'j' },
    { Onyx::Key::K, 'k' },
    { Onyx::Key::L, 'l' },
    { Onyx::Key::M, 'm' },
    { Onyx::Key::N, 'n' },
    { Onyx::Key::O, 'o' },
    { Onyx::Key::P, 'p' },
    { Onyx::Key::Q, 'q' },
    { Onyx::Key::R, 'r' },
    { Onyx::Key::S, 's' },
    { Onyx::Key::T, 't' },
    { Onyx::Key::U, 'u' },
    { Onyx::Key::V, 'v' },
    { Onyx::Key::W, 'w' },
    { Onyx::Key::X, 'x' },
    { Onyx::Key::Y, 'y' },
    { Onyx::Key::Z, 'z' },
    { Onyx::Key::LeftBracket, '[' },
    { Onyx::Key::Backslash, '\\' },
    { Onyx::Key::RightBracket, ']' },
    { Onyx::Key::GraveAccent, '`' },
    { Onyx::Key::World1, '!' },
    { Onyx::Key::World2, '"' }
};

std::map<char, char> shiftMap = {
    { ' ', ' ' },
    { '\'', '\"' },
    { ',', '<' },
    { '-', '_' },
    { '.', '>' },
    { '/', '?' },
    { '0', ')' },
    { '1', '!' },
    { '2', '@' },
    { '3', '#' },
    { '4', '$' },
    { '5', '%' },
    { '6', '^' },
    { '7', '&' },
    { '8', '*' },
    { '9', '(' },
    { ';', ':' },
    { '=', '+' },
    { 'a', 'A' },
    { 'b', 'B' },
    { 'c', 'C' },
    { 'd', 'D' },
    { 'e', 'E' },
    { 'f', 'F' },
    { 'g', 'G' },
    { 'h', 'H' },
    { 'i', 'I' },
    { 'j', 'J' },
    { 'k', 'K' },
    { 'l', 'L' },
    { 'm', 'M' },
    { 'n', 'N' },
    { 'o', 'O' },
    { 'p', 'P' },
    { 'q', 'Q' },
    { 'r', 'R' },
    { 's', 'S' },
    { 't', 'T' },
    { 'u', 'U' },
    { 'v', 'V' },
    { 'w', 'W' },
    { 'x', 'X' },
    { 'y', 'Y' },
    { 'z', 'Z' },
    { '[', '{' },
    { '\\', '|' },
    { ']', '}' },
    { '`', '~' },
    { '!', '1' },
    { '"', '2' }
};

std::map<char, char> unshiftMap = {
    { ' ', ' ' },
    { '\"', '\'' },
    { '<', ',' },
    { '_', '-' },
    { '>', '.' },
    { '?', '/' },
    { ')', '0' },
    { '!', '1' },
    { '@', '2' },
    { '#', '3' },
    { '$', '4' },
    { '%', '5' },
    { '^', '6' },
    { '&', '7' },
    { '*', '8' },
    { '(', '9' },
    { ':', ';' },
    { '+', '=' },
    { 'A', 'a' },
    { 'B', 'b' },
    { 'C', 'c' },
    { 'D', 'd' },
    { 'E', 'e' },
    { 'F', 'f' },
    { 'G', 'g' },
    { 'H', 'h' },
    { 'I', 'i' },
    { 'J', 'j' },
    { 'K', 'k' },
    { 'L', 'l' },
    { 'M', 'm' },
    { 'N', 'n' },
    { 'O', 'o' },
    { 'P', 'p' },
    { 'Q', 'q' },
    { 'R', 'r' },
    { 'S', 's' },
    { 'T', 't' },
    { 'U', 'u' },
    { 'V', 'v' },
    { 'W', 'w' },
    { 'X', 'x' },
    { 'Y', 'y' },
    { 'Z', 'z' },
    { '{', '[' },
    { '|', '\\' },
    { '}', ']' },
    { '~', '`' },
    { '1', '!' },
    { '2', '"' }
};

Onyx::Key ck::ctok(char c)
{
    return charToKeyMap[c];
}

char ck::ktoc(Onyx::Key key)
{
    return keyToCharMap[key];
}

char ck::shift(char c)
{
    return shiftMap[c];
}

char ck::unshift(char c)
{
    return unshiftMap[c];
}
